--liquibase formatted sql

--changeset museotekbox:0001-create-users
--comment JIT-provisioned local mirror of a Keycloak identity, keyed by JWT subject
CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject            VARCHAR(255) NOT NULL,
    email              VARCHAR(255),
    preferred_username VARCHAR(255),
    display_name       VARCHAR(255),
    first_seen_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_seen_at       TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_users_subject UNIQUE (subject)
);
--rollback DROP TABLE users;

--changeset museotekbox:0002-create-projects
--comment Local companion row for a Catalogue project, keyed by Catalogue's own project UUID
CREATE TABLE projects
(
    id         UUID PRIMARY KEY,
    org_id     UUID         NOT NULL,
    name       VARCHAR(255) NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);
--rollback DROP TABLE projects;

--changeset museotekbox:0003-create-boxes
--comment Physical RFID box, optionally pointed at a currently-active Project
CREATE TABLE boxes
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id             UUID         NOT NULL,
    name               VARCHAR(255) NOT NULL,
    serial_number      VARCHAR(255) NOT NULL,
    status             VARCHAR(255) NOT NULL,
    current_project_id UUID,
    CONSTRAINT uk_boxes_serial_number UNIQUE (serial_number),
    CONSTRAINT fk_boxes_current_project FOREIGN KEY (current_project_id) REFERENCES projects (id)
);
--rollback DROP TABLE boxes;

--changeset museotekbox:0004-create-box-projects
--comment Join table for a Box's assigned Projects (many-to-many)
CREATE TABLE box_projects
(
    box_id     BIGINT NOT NULL,
    project_id UUID   NOT NULL,
    PRIMARY KEY (box_id, project_id),
    CONSTRAINT fk_box_projects_box FOREIGN KEY (box_id) REFERENCES boxes (id),
    CONSTRAINT fk_box_projects_project FOREIGN KEY (project_id) REFERENCES projects (id)
);
--rollback DROP TABLE box_projects;

--changeset museotekbox:0005-create-scan-object-types
--comment Org-defined grouping of scan objects (e.g. "Muses", "True/False")
CREATE TABLE scan_object_types
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id UUID         NOT NULL,
    name   VARCHAR(255) NOT NULL
);
--rollback DROP TABLE scan_object_types;

--changeset museotekbox:0006-create-scan-objects
--comment Base table of the ScanObject JOINED-inheritance hierarchy; "kind" is the Hibernate discriminator column
CREATE TABLE scan_objects
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind                VARCHAR(31)  NOT NULL,
    org_id              UUID         NOT NULL,
    scan_object_type_id BIGINT,
    name                VARCHAR(255) NOT NULL,
    rfid_tag            VARCHAR(255),
    reusable            BOOLEAN      NOT NULL,
    CONSTRAINT uk_scan_objects_rfid_tag UNIQUE (rfid_tag),
    CONSTRAINT fk_scan_objects_type FOREIGN KEY (scan_object_type_id) REFERENCES scan_object_types (id)
);
--rollback DROP TABLE scan_objects;

--changeset museotekbox:0007-create-coloured-cards
--comment JOINED-inheritance subtype: a physical coloured card
CREATE TABLE coloured_cards
(
    id     BIGINT PRIMARY KEY,
    colour VARCHAR(255) NOT NULL,
    CONSTRAINT fk_coloured_cards_scan_object FOREIGN KEY (id) REFERENCES scan_objects (id)
);
--rollback DROP TABLE coloured_cards;

--changeset museotekbox:0008-create-drafts
--comment JOINED-inheritance subtype: a digital-only customizable card, no extra columns yet
CREATE TABLE drafts
(
    id BIGINT PRIMARY KEY,
    CONSTRAINT fk_drafts_scan_object FOREIGN KEY (id) REFERENCES scan_objects (id)
);
--rollback DROP TABLE drafts;

--changeset museotekbox:0009-create-printed-images
--comment JOINED-inheritance subtype: a card with a printed image
CREATE TABLE printed_images
(
    id        BIGINT PRIMARY KEY,
    image_url VARCHAR(255) NOT NULL,
    CONSTRAINT fk_printed_images_scan_object FOREIGN KEY (id) REFERENCES scan_objects (id)
);
--rollback DROP TABLE printed_images;

--changeset museotekbox:0010-create-three-d-printed-objects
--comment JOINED-inheritance subtype: a physical 3D-printed replica
CREATE TABLE three_d_printed_objects
(
    id        BIGINT PRIMARY KEY,
    model_ref VARCHAR(255) NOT NULL,
    CONSTRAINT fk_three_d_printed_objects_scan_object FOREIGN KEY (id) REFERENCES scan_objects (id)
);
--rollback DROP TABLE three_d_printed_objects;
