--liquibase formatted sql

--changeset museotekbox:0011-create-scenes
--comment A chapter of an experience, scoped to a Project; stable scene_key used by the experience document instead of the numeric id
CREATE TABLE scenes
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        UUID         NOT NULL,
    scene_key         VARCHAR(64)  NOT NULL,
    name              VARCHAR(255) NOT NULL,
    position          INTEGER      NOT NULL,
    is_start          BOOLEAN      NOT NULL DEFAULT FALSE,
    init_card_type_id BIGINT,
    CONSTRAINT fk_scenes_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_scenes_init_card_type FOREIGN KEY (init_card_type_id) REFERENCES scan_object_types (id),
    CONSTRAINT uk_scenes_project_key UNIQUE (project_id, scene_key)
);
--rollback DROP TABLE scenes;

--changeset museotekbox:0012-create-blocks
--comment A piece of content inside a Scene; content is a single JSONB column, shape depends on type
CREATE TABLE blocks
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id  BIGINT       NOT NULL,
    block_key VARCHAR(64)  NOT NULL,
    type      VARCHAR(31)  NOT NULL,
    position  INTEGER      NOT NULL,
    content   JSONB        NOT NULL DEFAULT '{}',
    CONSTRAINT fk_blocks_scene FOREIGN KEY (scene_id) REFERENCES scenes (id),
    CONSTRAINT uk_blocks_scene_key UNIQUE (scene_id, block_key)
);
--rollback DROP TABLE blocks;

--changeset museotekbox:0013-create-rules
--comment What happens when something occurs in a Scene (a scan, an answer, a video finishing); owned by Scene, not Block
CREATE TABLE rules
(
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id             BIGINT       NOT NULL,
    rule_key             VARCHAR(64)  NOT NULL,
    event_type           VARCHAR(31)  NOT NULL,
    action               VARCHAR(31)  NOT NULL,
    position             INTEGER      NOT NULL,
    scan_object_type_id  BIGINT,
    trigger_block_key    VARCHAR(64),
    target_scene_key     VARCHAR(64),
    target_block_key     VARCHAR(64),
    CONSTRAINT fk_rules_scene FOREIGN KEY (scene_id) REFERENCES scenes (id),
    CONSTRAINT fk_rules_scan_object_type FOREIGN KEY (scan_object_type_id) REFERENCES scan_object_types (id),
    CONSTRAINT uk_rules_scene_key UNIQUE (scene_id, rule_key)
);
--rollback DROP TABLE rules;

--changeset museotekbox:0014-add-experience-doc-columns
--comment Per-project running counters for scene/block/rule keys, plus the experience document's optimistic-concurrency version
ALTER TABLE projects
    ADD COLUMN next_scene_seq INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN next_block_seq INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN next_rule_seq  INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN doc_version    INTEGER NOT NULL DEFAULT 0;
--rollback ALTER TABLE projects DROP COLUMN next_scene_seq, DROP COLUMN next_block_seq, DROP COLUMN next_rule_seq, DROP COLUMN doc_version;
