--liquibase formatted sql

--changeset museotekbox:0015-create-experience-flows
--comment The curator's source for an experience (start, activities, hand-overs, end, replies), 1:1 with the project; stored as-is, versioned with projects.doc_version
CREATE TABLE experience_flows
(
    project_id     UUID    PRIMARY KEY,
    schema_version INTEGER NOT NULL,
    flow           JSONB   NOT NULL,
    CONSTRAINT fk_experience_flows_project FOREIGN KEY (project_id) REFERENCES projects (id)
);
--rollback DROP TABLE experience_flows;

--changeset museotekbox:0016-create-experience-variables
--comment Per-experience number/flag variables that rule effects change and rule conditions test
CREATE TABLE experience_variables
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    UUID        NOT NULL,
    variable_key  VARCHAR(64) NOT NULL,
    kind          VARCHAR(15) NOT NULL,
    initial_value VARCHAR(64) NOT NULL,
    CONSTRAINT fk_experience_variables_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT uk_experience_variables_key UNIQUE (project_id, variable_key)
);
--rollback DROP TABLE experience_variables;

--changeset museotekbox:0017-add-rule-v2-columns
--comment Rule model v2 (trigger + condition + effects + destination), added nullable next to the old columns so the current code keeps working; the old columns are dropped when the code switches over
ALTER TABLE rules
    ADD COLUMN trigger_type     VARCHAR(31),
    ADD COLUMN trigger_seconds  INTEGER,
    ADD COLUMN condition        JSONB,
    ADD COLUMN effects          JSONB NOT NULL DEFAULT '[]',
    ADD COLUMN destination_type VARCHAR(15);
--rollback ALTER TABLE rules DROP COLUMN trigger_type, DROP COLUMN trigger_seconds, DROP COLUMN condition, DROP COLUMN effects, DROP COLUMN destination_type;
